// Appendix A: Installation and Setup -- Building CUDA Hammer's Toolchain
// 096_one_combined_toolchain_report_the_capstone.cpp
//
// Section A.4 (capstone) -- Sections A.1-A.3 each checked one real
// piece of the toolchain this book needs (the real minimum C++
// standard, the real vector ISA, an optional CUDA toolkit). This file
// combines the two machine-portable checks (A.1's real __cplusplus
// value, A.2's real /proc/cpuinfo-based ISA detection) into ONE
// consolidated report, plain C++ with no CUDA linkage -- so, per this
// book's own standing cross-machine rule, it is cross-verified on
// BOTH the cloud sandbox and the device. Its own real output on each
// machine is then checked directly against what TOC.md's own "Status"
// section already claimed about each machine, closing the loop: not
// re-asserting those claims, RE-VERIFYING them.
//
// Compile: g++ -std=c++17 -Wall -Wextra -O2 096_one_combined_toolchain_report_the_capstone.cpp -o 096_driver
// Run:     ./096_driver

#include <cstdio>
#include <fstream>
#include <memory>
#include <sstream>
#include <string>
#include <vector>

static std::vector<std::string> readRealCpuFlags() {
    std::ifstream f("/proc/cpuinfo");
    std::vector<std::string> flags;
    std::string line;
    while (std::getline(f, line)) {
        if (line.rfind("flags", 0) == 0 || line.rfind("Features", 0) == 0) {
            std::istringstream iss(line);
            std::string token;
            while (iss >> token) flags.push_back(token);
            break;
        }
    }
    return flags;
}

static bool hasFlag(const std::vector<std::string>& flags, const std::string& want) {
    for (const auto& f : flags) if (f == want) return true;
    return false;
}

int main() {
    printf("=== Appendix A.4 (capstone): one combined toolchain report ===\n\n");

    // ---- A.1's own check, folded in here: real __cplusplus value ----
    long cxxStd = static_cast<long>(__cplusplus);
    printf("[A.1] real __cplusplus = %ldL", cxxStd);
    if (cxxStd >= 201703L) printf(" (C++17 or newer -- this book's own -std=c++17 convention met)\n");
    else if (cxxStd >= 201402L) printf(" (C++14 -- CUDA Hammer's own real minimum, per Section A.1's sweep, but below this book's own -std=c++17 convention)\n");
    else printf(" (below C++14 -- CUDA Hammer's own real minimum; this book's code will not compile)\n");
    // A real std::make_unique allocation -- if this line itself failed
    // to compile, this file would never have reached main() at all, so
    // its presence here is itself a live re-check of A.1's own finding.
    auto probe = std::make_unique<int>(1);
    printf("      std::make_unique probe object: %d (confirms C++14's own std::make_unique compiled)\n\n", *probe);

    // ---- A.2's own check, folded in here: real ISA detection ----
#if defined(__x86_64__)
    printf("[A.2] compile-time architecture: __x86_64__ -- Chapter 19 targets Isa::Avx2 here\n");
    std::vector<std::string> flags = readRealCpuFlags();
    bool avx2 = hasFlag(flags, "avx2"), fma = hasFlag(flags, "fma"), avx512f = hasFlag(flags, "avx512f");
    printf("      real /proc/cpuinfo: avx2=%s fma=%s avx512f=%s\n",
           avx2 ? "yes" : "no", fma ? "yes" : "no", avx512f ? "yes" : "no");
#elif defined(__aarch64__)
    printf("[A.2] compile-time architecture: __aarch64__ -- Chapter 19 targets Isa::Neon here\n");
    std::vector<std::string> flags = readRealCpuFlags();
    bool asimd = hasFlag(flags, "asimd");
    printf("      real /proc/cpuinfo: asimd=%s\n", asimd ? "yes" : "no");
#else
    printf("[A.2] neither __x86_64__ nor __aarch64__ -- outside Chapter 19's own two real targets\n");
#endif

    printf("\n[A.3] CUDA toolkit (nvcc): checked separately (Section A.3), since this plain\n");
    printf("      C++ file carries no CUDA linkage -- run 095's own driver directly on this\n");
    printf("      machine, or check `nvcc --version` at a shell, to confirm it here too.\n\n");

    printf("=== real result: this machine's own toolchain report, generated by actually\n");
    printf("running compiled code on it, not copied from another machine's report ===\n");
    return 0;
}
