# Chapter 29, File 075: Flash Attention's own algorithmic core -- online
# (streaming) softmax over tiled key/value blocks -- implemented in pure
# NumPy (no torch, no triton, no jax, no tvm) so this file cross-verifies
# byte-for-byte identical on both the cloud sandbox and the device, the
# same discipline as every plain-C++ Part 1-5 chapter.
#
# Real motivation, tied directly back to this book's own Part 3: Chapter
# 14's own reductionFusionPass() treats a Sum node's OUTPUT as always
# external, any consumer count -- but every Sum node Chapters 9-24 ever
# generated code for assumed the reduction's own INPUT was already fully
# materialized before the reduction ran. Softmax needs TWO reductions
# per row (a max, then a sum of exp(x - max)) over the attention score
# matrix, and that matrix is N-by-M -- for real transformer sequence
# lengths (N, M in the thousands), materializing it is the real memory
# bottleneck FlashAttention (Dao et al., 2022, arXiv:2205.14135) was
# built to remove. The trick that makes it possible predates that paper:
# Milakov & Gimelshein's "Online normalizer calculation for softmax"
# (2018, arXiv:1805.02867) shows a running max/sum can be updated
# incrementally, one block of columns at a time, WITHOUT ever holding
# the full row in memory at once -- provided each time the running max
# increases, the previously accumulated sum and output are rescaled by
# exp(old_max - new_max) to stay consistent. This file proves that
# rescaling step is correct by comparing its real output, bit-for-bit
# within float64 tolerance, against naive full-materialization softmax
# attention on the same real random inputs.
#
# Compiled with:   python3 "075_naive_vs_online_softmax_flash_attention_pure_numpy.py"

import numpy as np


def naive_attention(q, k, v):
    """The textbook definition: materializes the FULL (N, M) score matrix,
    exactly the "compute everything, then reduce" shape every Sum node
    generated by Chapter 14's own reductionFusionPass() has always
    assumed. Returns (output, the full softmax row-sums) so File 077 can
    compare its own real logsumexp finding against something computed
    here independently."""
    n, d = q.shape
    m = k.shape[0]
    scale = 1.0 / np.sqrt(d)
    scores = (q @ k.T) * scale  # (N, M) -- THE memory bottleneck
    row_max = scores.max(axis=1, keepdims=True)  # (N, 1)
    exp_scores = np.exp(scores - row_max)  # (N, M)
    row_sum = exp_scores.sum(axis=1, keepdims=True)  # (N, 1)
    probs = exp_scores / row_sum  # (N, M)
    out = probs @ v  # (N, d)
    return out, row_max.reshape(-1), row_sum.reshape(-1)


def flash_attention(q, k, v, block_size_kv):
    """FlashAttention's own algorithmic core: for each query row, stream
    the key/value blocks one at a time, keeping only a RUNNING max,
    RUNNING sum, and RUNNING (unnormalized) output -- never materializing
    the full (N, M) score matrix. `block_size_kv` deliberately does not
    evenly divide M (checked by the caller), forcing a genuine tail
    block, the same "don't pick numbers that hide the edge case" practice
    this book has followed since Chapter 19's own n=11 vector-width test."""
    n, d = q.shape
    m = k.shape[0]
    scale = 1.0 / np.sqrt(d)

    running_max = np.full(n, -np.inf)
    running_sum = np.zeros(n)
    running_out = np.zeros((n, d))

    num_blocks = 0
    peak_block_bytes = 0
    for start in range(0, m, block_size_kv):
        end = min(start + block_size_kv, m)
        k_block = k[start:end]  # (Bc, d) -- Bc <= block_size_kv
        v_block = v[start:end]  # (Bc, d)
        num_blocks += 1

        block_scores = (q @ k_block.T) * scale  # (N, Bc) -- ONLY this
        # block's own score tile is ever in memory, never the full (N, M)
        block_bytes = block_scores.nbytes
        peak_block_bytes = max(peak_block_bytes, block_bytes)

        block_max = block_scores.max(axis=1)  # (N,)
        new_max = np.maximum(running_max, block_max)  # (N,)

        # The online-softmax rescaling step itself (Milakov & Gimelshein,
        # 2018): whatever was already accumulated under the OLD running
        # max gets corrected by exp(old_max - new_max) before this
        # block's own contribution is added under the NEW running max.
        correction = np.exp(running_max - new_max)  # (N,) -- 0 on the
        # very first block, where running_max starts at -inf and
        # correction would be exp(-inf - finite) = 0, which is exactly
        # right: there is nothing yet to rescale.
        correction = np.nan_to_num(correction, nan=0.0)

        p_block = np.exp(block_scores - new_max[:, None])  # (N, Bc)
        block_sum = p_block.sum(axis=1)  # (N,)

        running_sum = running_sum * correction + block_sum
        running_out = (running_out * correction[:, None]
                       + p_block @ v_block)
        running_max = new_max

    out = running_out / running_sum[:, None]
    return out, running_max, running_sum, num_blocks, peak_block_bytes


if __name__ == "__main__":
    rng = np.random.default_rng(seed=29)

    n, m, d = 8, 13, 4  # M=13 deliberately not a multiple of any small
    # block size below -- every block_size_kv candidate forces a real
    # tail block, the same discipline Chapter 19's own n=11 test used.
    q = rng.standard_normal((n, d))
    k = rng.standard_normal((m, d))
    v = rng.standard_normal((m, d))

    naive_out, naive_max, naive_sum = naive_attention(q, k, v)

    print(f"Naive attention: Q({n}x{d}) @ K({m}x{d}).T -> scores({n}x{m}), "
          f"the full matrix FlashAttention's own algorithm never "
          f"materializes.")
    print(f"Naive scores matrix: {n * m} floats, "
          f"{n * m * 8} bytes (float64) held at once.")
    print()

    for block_size_kv in (4, 5, 13):
        (flash_out, flash_max, flash_sum,
         num_blocks, peak_block_bytes) = flash_attention(q, k, v, block_size_kv)
        max_abs_diff = np.abs(naive_out - flash_out).max()
        match = np.allclose(naive_out, flash_out, atol=1e-10)
        max_match = np.allclose(naive_max, flash_max, atol=1e-12)
        sum_match = np.allclose(naive_sum, flash_sum, atol=1e-10)
        print(f"block_size_kv={block_size_kv:2d}: {num_blocks} real KV "
              f"block(s) (last block size "
              f"{m - block_size_kv * (num_blocks - 1)}), peak per-block "
              f"score tile = {peak_block_bytes} bytes -- output match = "
              f"{match} (max abs diff {max_abs_diff:.3e}), running max "
              f"matches naive row-max = {max_match}, running sum matches "
              f"naive row-sum = {sum_match}")

    print()
    print("Real, concrete memory argument at a realistic scale "
          "(N=M=1024 queries/keys, d=64, float32, block_size_kv=128, "
          "computed here, not measured -- this file's own real n=8/m=13 "
          "arrays are too small to show a meaningful byte comparison):")
    real_n, real_m, real_d, real_block = 1024, 1024, 64, 128
    naive_bytes = real_n * real_m * 4
    flash_peak_bytes = real_n * real_block * 4
    print(f"  naive materialized score matrix: {naive_bytes:,} bytes "
          f"({naive_bytes / 1024:.0f} KB)")
    print(f"  flash peak per-block score tile: {flash_peak_bytes:,} bytes "
          f"({flash_peak_bytes / 1024:.0f} KB) -- "
          f"{naive_bytes / flash_peak_bytes:.1f}x smaller, at the SAME "
          f"real sequence length")
